name: SimCube BuildTool
description: Executes the SimCube Build Tool with the Supplied ENVs.

runs:
  using: composite
  steps:
    - run: echo "::add-matcher::${GITHUB_ACTION_PATH}/matcher.json"
      shell: bash
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
    - run: echo "::remove-matcher owner=bash-action::"
      shell: bash
