name: SimCube BuildTool
description: Executes the SimCube Build Tool with the Supplied ENVs.

inputs:
  packableProjects:
    description: Base64 encoded json payload for Packable Project settings.
    required: false
    default: "e30="
  imageDetails:
    description: Base64 encoded json payload for OCI Images to Build.
    required: false
    default: "e30="
  setupDotNet:
    description: Boolean flag which declares if dotnet should be setup.
    required: false
    default: 'false'
  checkout:
    description: Boolean flag which declares if git checkout should take place or not by this script.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    
    - if: ${{ inputs.checkout == 'true' }} 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - if: ${{ inputs.setupDotNet == 'true' }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
      
    - run: echo "::add-matcher::${GITHUB_ACTION_PATH}/matcher.json"
      shell: bash
      
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/script.sh ${{ inputs.packableProjects }} ${{ inputs.imageDetails }}
      shell: bash
      
    - run: echo "::remove-matcher owner=bash-action::"
      shell: bash
